services:
  matsin:
    build:
      context: .
      dockerfile: ./docker/mediawiki/Dockerfile
      target: mediawiki_run_stage
      args:
        - MEDIA_WIKI_VERSION=1.42
        - BRANCH_TAG=REL1_42
        - INSTANCE_BUILD=matsin
    container_name: dansin_matsin
    ports:
      - "8080:80"
    environment:
      - MEDIAWIKI_DB_TYPE=${MATSIN_DB_TYPE}
      - MEDIAWIKI_DB_HOST=${MATSIN_DB_HOST}
      - MEDIAWIKI_DB_PORT=${MATSIN_DB_PORT}
      - MEDIAWIKI_DB_NAME=${MATSIN_DB_NAME}
      - MEDIAWIKI_DB_USER=${MATSIN_DB_USER}
      - MEDIAWIKI_DB_PASSWORD=${MATSIN_DB_PASSWORD}
    volumes:
      - ./backups/matsin:/backups
      - ./public/matsin:/var/www/html/public
      - ./settings/matsin/LocalSettings.php:/var/www/html/LocalSettings.php
      - matsin_medias:/var/www/html/mediafiles
    depends_on:
      - db
    networks:
      - brdgnet

  vazhsin:
    build:
      context: .
      dockerfile: ./docker/mediawiki/Dockerfile
      target: mediawiki_run_stage
      args:
        - MEDIA_WIKI_VERSION=1.42
        - BRANCH_TAG=REL1_42
        - INSTANCE_BUILD=vazhsin
    container_name: dansin_vazhsin
    ports:
      - "8081:80"
    environment:
      - MEDIAWIKI_DB_TYPE=${VAZHSIN_DB_TYPE}
      - MEDIAWIKI_DB_HOST=${VAZHSIN_DB_HOST}
      - MEDIAWIKI_DB_PORT=${VAZHSIN_DB_PORT}
      - MEDIAWIKI_DB_NAME=${VAZHSIN_DB_NAME}
      - MEDIAWIKI_DB_USER=${VAZHSIN_DB_USER}
      - MEDIAWIKI_DB_PASSWORD=${VAZHSIN_DB_PASSWORD}
    volumes:
      - ./backups/vazhsin:/backups
      - ./public/vazhsin:/var/www/html/public
      - ./settings/vazhsin/LocalSettings.php:/var/www/html/LocalSettings.php
      - vazhsin_medias:/var/www/html/mediafiles
    depends_on:
      - db
    networks:
      - brdgnet

  resasin:
    build:
      context: .
      dockerfile: ./docker/mediawiki/Dockerfile
      target: mediawiki_run_stage
      args:
        - MEDIA_WIKI_VERSION=1.42
        - BRANCH_TAG=REL1_42
        - INSTANCE_BUILD=resasin
    container_name: dansin_resasin
    ports:
      - "8082:80"
    environment:
      - MEDIAWIKI_DB_TYPE=${RESASIN_DB_TYPE}
      - MEDIAWIKI_DB_HOST=${RESASIN_DB_HOST}
      - MEDIAWIKI_DB_PORT=${RESASIN_DB_PORT}
      - MEDIAWIKI_DB_NAME=${RESASIN_DB_NAME}
      - MEDIAWIKI_DB_USER=${RESASIN_DB_USER}
      - MEDIAWIKI_DB_PASSWORD=${RESASIN_DB_PASSWORD}
    volumes:
      - ./backups/resasin:/backups
      - ./public/resasin:/var/www/html/public
      - ./settings/resasin/LocalSettings.php:/var/www/html/LocalSettings.php
      - resasin_medias:/var/www/html/mediafiles
    depends_on:
      - db
    networks:
      - brdgnet

  tajrosin:
    build:
      context: .
      dockerfile: ./docker/mediawiki/Dockerfile
      target: mediawiki_run_stage
      args:
        - MEDIA_WIKI_VERSION=1.42
        - BRANCH_TAG=REL1_42
        - INSTANCE_BUILD=tajrosin
    container_name: dansin_tajrosin
    ports:
      - "8083:80"
    environment:
      - MEDIAWIKI_DB_TYPE=${TAJROSIN_DB_TYPE}
      - MEDIAWIKI_DB_HOST=${TAJROSIN_DB_HOST}
      - MEDIAWIKI_DB_PORT=${TAJROSIN_DB_PORT}
      - MEDIAWIKI_DB_NAME=${TAJROSIN_DB_NAME}
      - MEDIAWIKI_DB_USER=${TAJROSIN_DB_USER}
      - MEDIAWIKI_DB_PASSWORD=${TAJROSIN_DB_PASSWORD}
    volumes:
      - ./backups/tajrosin:/backups
      - ./public/tajrosin:/var/www/html/public
      - ./settings/tajrosin/LocalSettings.php:/var/www/html/LocalSettings.php
      - tajrosin_medias:/var/www/html/mediafiles
    depends_on:
      - db
    networks:
      - brdgnet

  amoosin:
    build:
      context: .
      dockerfile: ./docker/mediawiki/Dockerfile
      target: mediawiki_run_stage
      args:
        - MEDIA_WIKI_VERSION=1.42
        - BRANCH_TAG=REL1_42
        - INSTANCE_BUILD=amoosin
    container_name: dansin_amoosin
    ports:
      - "8084:80"
    environment:
      - MEDIAWIKI_DB_TYPE=${AMOOSIN_DB_TYPE}
      - MEDIAWIKI_DB_HOST=${AMOOSIN_DB_HOST}
      - MEDIAWIKI_DB_PORT=${AMOOSIN_DB_PORT}
      - MEDIAWIKI_DB_NAME=${AMOOSIN_DB_NAME}
      - MEDIAWIKI_DB_USER=${AMOOSIN_DB_USER}
      - MEDIAWIKI_DB_PASSWORD=${AMOOSIN_DB_PASSWORD}
    volumes:
      - ./backups/amoosin:/backups
      - ./public/amoosin:/var/www/html/public
      - ./settings/amoosin/LocalSettings.php:/var/www/html/LocalSettings.php
      - amoosin_medias:/var/www/html/mediafiles
    depends_on:
      - db
    networks:
      - brdgnet

  bonchsin:
    build:
      context: .
      dockerfile: ./docker/mediawiki/Dockerfile
      target: mediawiki_run_stage
      args:
        - MEDIA_WIKI_VERSION=1.42
        - BRANCH_TAG=REL1_42
        - INSTANCE_BUILD=bonchsin
    container_name: dansin_bonchsin
    ports:
      - "8085:80"
    environment:
      - MEDIAWIKI_DB_TYPE=${BONCHSIN_DB_TYPE}
      - MEDIAWIKI_DB_HOST=${BONCHSIN_DB_HOST}
      - MEDIAWIKI_DB_PORT=${BONCHSIN_DB_PORT}
      - MEDIAWIKI_DB_NAME=${BONCHSIN_DB_NAME}
      - MEDIAWIKI_DB_USER=${BONCHSIN_DB_USER}
      - MEDIAWIKI_DB_PASSWORD=${BONCHSIN_DB_PASSWORD}
    volumes:
      - ./backups/bonchsin:/backups
      - ./public/bonchsin:/var/www/html/public
      - ./settings/bonchsin/LocalSettings.php:/var/www/html/LocalSettings.php
      - bonchsin_medias:/var/www/html/mediafiles
    depends_on:
      - db
      - drawio
    networks:
      - brdgnet

  vazhsin_next:
    build:
      context: .
      dockerfile: ./docker/mediawiki/Dockerfile
      target: mediawiki_run_stage
      args:
        - MEDIA_WIKI_VERSION=1.42
        - BRANCH_TAG=REL1_42
        - INSTANCE_BUILD=vazhsin_next
    container_name: dansin_vazhsin_next
    ports:
      - "8086:80"
    environment:
      - MEDIAWIKI_DB_TYPE=${VAZHSIN_NEXT_DB_TYPE}
      - MEDIAWIKI_DB_HOST=${VAZHSIN_NEXT_DB_HOST}
      - MEDIAWIKI_DB_PORT=${VAZHSIN_NEXT_DB_PORT}
      - MEDIAWIKI_DB_NAME=${VAZHSIN_NEXT_DB_NAME}
      - MEDIAWIKI_DB_USER=${VAZHSIN_NEXT_DB_USER}
      - MEDIAWIKI_DB_PASSWORD=${VAZHSIN_NEXT_DB_PASSWORD}
    volumes:
      - ./backups/vazhsin_next:/backups
      - ./public/vazhsin_next:/var/www/html/public
      - ./settings/vazhsin_next/LocalSettings.php:/var/www/html/LocalSettings.php
      - vazhsin_next_medias:/var/www/html/mediafiles
    depends_on:
      - db
    networks:
      - brdgnet

  amookhsin:
    build:
      context: .
      dockerfile: ./docker/mediawiki/Dockerfile
      target: mediawiki_run_stage
      args:
        - MEDIA_WIKI_VERSION=1.42
        - BRANCH_TAG=REL1_42
        - INSTANCE_BUILD=amookhsin
    container_name: dansin_amookhsin
    ports:
      - "8087:80"
    environment:
      - MEDIAWIKI_DB_TYPE=${AMOOKHSIN_DB_TYPE}
      - MEDIAWIKI_DB_HOST=${AMOOKHSIN_DB_HOST}
      - MEDIAWIKI_DB_PORT=${AMOOKHSIN_DB_PORT}
      - MEDIAWIKI_DB_NAME=${AMOOKHSIN_DB_NAME}
      - MEDIAWIKI_DB_USER=${AMOOKHSIN_DB_USER}
      - MEDIAWIKI_DB_PASSWORD=${AMOOKHSIN_DB_PASSWORD}
    volumes:
      - ./backups/amookhsin:/backups
      - ./public/amookhsin:/var/www/html/public
      - ./settings/amookhsin/LocalSettings.php:/var/www/html/LocalSettings.php
      - amookhsin_medias:/var/www/html/mediafiles
    depends_on:
      - db
      - drawio
    networks:
      - brdgnet

  drawio:
    image: jgraph/drawio
    container_name: dansin_drawio
    volumes:
      - drawio_data:/data
    ports:
      - "8089:8080"
    networks:
      - brdgnet

  db:
    build:
      context: ./docker/mariadb
      dockerfile: Dockerfile
      target: mariadb_run_stage
      args:
        - MARIADB_VERSION=11.2
    container_name: dansin_db
    env_file:
      - .env
    volumes:
      - ./backups:/backups
      - dansin_data:/var/lib/mysql
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    networks:
      - brdgnet

  phpmyadmin:
    image: phpmyadmin:5.2
    container_name: dansin_admin
    ports:
      - "8090:80"
    env_file:
      - .env

    networks:
      - brdgnet

networks:
  brdgnet:
    driver: bridge

volumes:
  # Define an external volume named matsin_medias
  matsin_medias: {}
  # Define an external volume named vazhsin_medias
  vazhsin_medias: {}
  # Define an external volume named vazhsin_next_medias
  vazhsin_next_medias: {}
  # Define an external volume named tajrosin_medias
  tajrosin_medias: {}
  # Define an external volume named resasin_medias
  resasin_medias: {}
  # Define an external volume named amoosin_medias
  amoosin_medias: {}
  # Define an external volume named bonchsin_medias
  bonchsin_medias: {}
  # Define an external volume named amookhsin_medias
  amookhsin_medias: {}
  # Define an external volume named dansin_data
  dansin_data: {}
  # Define an external volume named drawio_data
  drawio_data: {}
