#!/usr/bin/env bash

# Function to initializa the database
init() {
    local initial_backup="$1"
    message_welcome "You are about to initialize the database with factory data."
    yarsin restore md -n "${initial_backup}" &&
        message_success "The initialization process has been successfully completed. You can now start using your wikis..."
}

init "$@"
