#!/usr/bin/env bash

if [[ $# -eq 0 ]]; then
    docker compose -f "${docker_compose}" down "${DEFAULT_SERVICE}"
else
    docker compose -f "${docker_compose}" down "$@"
fi

# Check if containers for matsin, vazhsin, and resasin services are not running
if ! docker compose ps --format '{{.Names}}' | grep -q -E '(vazhsin|vazhsin_next|matsin|resasin|tajrosin|amoosin|bonchsin|amookhsin)$'; then
    docker compose -f "${docker_compose}" down # Stop all services
fi
