#!/usr/bin/env bash

# Function: init
# Description: Initialize the database
# Arguments:
#   None
init() {
    local backup_name="${1}"
    local was_running=1

    if ! docker_service_is_running "db"; then
        was_running=0
    fi

    # Execute backup command for the database management system
    docker compose -f "${docker_compose}" down db -v
    docker compose -f "${docker_compose}" up db -d
    docker compose -f "${docker_compose}" exec db bash -c "yarsin init ${INITIAL_BACKUP}"

    if [ ${was_running} = 1 ]; then
        docker compose -f "${docker_compose}" restart db
    else
        docker compose -f $"docker_compose" down db
    fi
}

init "$@"
