<?php
# This file was automatically generated by the MediaWiki 1.42.1
# installer. If you make manual changes, please keep track in case you
# need to recreate them later.
#
# See includes/MainConfigSchema.php for all configurable settings
# and their default values, but don't forget to make changes in _this_
# file, not there.
#
# Further documentation for configuration settings may be found at:
# https://www.mediawiki.org/wiki/Manual:Configuration_settings

# Protect against web entry
if (!defined('MEDIAWIKI')) {
	exit;
}

## Uncomment this to disable output compression
# $wgDisableOutputCompression = true;

$wgSitename = 'آموسین';

## The URL base path to the directory containing the wiki;
## defaults for all runtime URL paths are based off of this.
## For more information on customizing the URLs
## (like /w/index.php/Page_title to /wiki/Page_title) please see:
## https://www.mediawiki.org/wiki/Manual:Short_URL
$wgScriptPath = '';

// Define an array of actions to be used in the loop
$actions = [
	'edit',
	'watch',
	'unwatch',
	'delete',
	'revert',
	'rollback',
	'protect',
	'unprotect',
	'markpatrolled',
	'render',
	'submit',
	'history',
	'purge',
	'info',
];
// Assign a path for each action in the array
foreach ($actions as $action) {
	$wgActionPaths[$action] = "/wiki/$1/$action";
}
// Assign a path for the 'view' action
$wgActionPaths['view'] = "/wiki/$1";
// Set the article path to the 'view' action path
$wgArticlePath = $wgActionPaths['view'];

## The protocol and server name to use in fully-qualified URLs
$wgServer = 'http://localhost:8084';

## The URL path to static resources (images, scripts, etc.)
$wgResourceBasePath = $wgScriptPath;

## The URL paths to the logo.  Make sure you change this from the default,
## or else you'll overwrite your logo when you upgrade!
$wgLogos = [
	'1x' => "$wgResourceBasePath/public/logo.svg",
	'icon' => "$wgResourceBasePath/public/icon.svg",
];

// Set the favicon  
$wgFavicon = "$wgResourceBasePath/public/favicon.png";

## UPO means: this is also a user preference option

$wgEnableEmail = true;
$wgEnableUserEmail = true; # UPO

$wgEmergencyContact = 'noreply@localhost.com';
$wgPasswordSender = 'noreply@localhost.com';

$wgEnotifUserTalk = true; # UPO
$wgEnotifWatchlist = true; # UPO
$wgEmailAuthentication = true;

## Database settings
$wgDBtype = 'mysql';
$wgDBserver = 'db';
$wgDBname = 'amoosin_db';
$wgDBuser = 'amoosin';
$wgDBpassword = 'amoosin_password';

# MySQL specific settings
$wgDBprefix = "";
$wgDBssl = false;

# MySQL table options to use during installation or update
$wgDBTableOptions = "ENGINE=InnoDB, DEFAULT CHARSET=binary";

# Shared database table
# This has no effect unless $wgSharedDB is also set.
$wgSharedTables[] = "actor";

## Shared memory settings
$wgMainCacheType = CACHE_NONE;
$wgMemCachedServers = [];

## To enable image uploads, make sure the 'images' directory
## is writable, then set this to true:
$wgEnableUploads = true; // Enable file uploads in MediaWiki  
$wgUseImageMagick = true; // Use ImageMagick for image processing instead of GD  
$wgImageMagickConvertCommand = '/usr/bin/convert'; // Path to the ImageMagick convert command  
// Allow MP3 files  
$wgFileExtensions[] = 'mp3'; // Add 'mp3' to the list of allowed file extensions for uploads  
// Allow all image formats  
$wgFileExtensions = array_merge($wgFileExtensions, ['png', 'gif', 'jpg', 'jpeg', 'svg', 'bmp']); // Merge additional image formats into the allowed file extensions  
// Set the upload directory to /var/www/html/mediafiles  
$wgUploadDirectory = "$wgResourceBasePath/mediafiles"; // Specify the directory where uploaded files will be stored  
$wgUploadPath = "/mediafiles"; // Define the web-accessible path for uploaded files  
// Set the maximum upload file size to 2MB  
$wgMaxUploadSize = 2 * 1024 * 1024; // Limit the maximum file size for uploads to 2 megabytes (MB)

# InstantCommons allows wiki to use images from https://commons.wikimedia.org
$wgUseInstantCommons = false;

# Periodically send a pingback to https://www.mediawiki.org/ with basic data
# about this MediaWiki instance. The Wikimedia Foundation shares this data
# with MediaWiki developers to help guide future development efforts.
$wgPingback = true;

# Site language code, should be one of the list in ./includes/languages/data/Names.php
$wgLanguageCode = 'fa';

# Time zone
$wgDefaultTimeZone = 'Asia/Tehran';
// Set the calendar to the Iranian calendar (Jalali)  
$wgDefaultCalendar = 'jalali';

// Set the default date format to Jalali  
$wgDefaultDateFormat = 'jalali';

## Set $wgCacheDirectory to a writable directory on the web server
## to make your wiki go slightly faster. The directory should not
## be publicly accessible from the web.
#$wgCacheDirectory = "$IP/cache";

$wgSecretKey = 'b5371a668de584a84557381b3377afb3ab1d7013b58ca4e942d0602de568271e';

# Changing this will log out all existing sessions.
$wgAuthenticationTokenVersion = '1';

# Site upgrade key. Must be set to a string (default provided) to turn on the
# web installer while LocalSettings.php is in place
$wgUpgradeKey = 'd34732c38fbfefa1';

## For attaching licensing metadata to pages, and displaying an
## appropriate copyright notice / icon. GNU Free Documentation
## License and Creative Commons licenses are supported so far.
$wgRightsPage = ""; # Set to the title of a wiki page that describes your license/copyright
$wgRightsUrl = 'https://creativecommons.org/publicdomain/zero/1.0/deed.fa';
$wgRightsText = 'CC0 (Creative Commons Zero) [مالکیت عمومی]';
$wgRightsIcon = "$wgResourceBasePath/resources/assets/licenses/cc-0.png";

# Path to the GNU diff3 utility. Used for conflict resolution.
$wgDiff3 = '/usr/bin/diff3';

# The following permissions were set based on your choice in the installer
$wgGroupPermissions['*']['createaccount'] = false;
$wgGroupPermissions['*']['edit'] = false;

## Default skin: you can change the default skin. Use the internal symbolic
## names, e.g. 'vector' or 'monobook':
$wgDefaultSkin = 'vector-2022';
$wgDefaultMobileSkin = 'minerva';

# Enabled skins.
# The following skins were automatically enabled:
wfLoadSkin('MinervaNeue');
wfLoadSkin('MonoBook');
wfLoadSkin('Timeless');
wfLoadSkin('Vector');


# Enabled extensions. Most of the extensions are enabled by adding
# wfLoadExtension( 'ExtensionName' );
# to LocalSettings.php. Check specific extension documentation for more details.
# The following extensions were automatically enabled:
wfLoadExtension('CategoryTree');
wfLoadExtension('Cite');
wfLoadExtension('CiteThisPage');
wfLoadExtension('CodeEditor');
wfLoadExtension('Gadgets');
wfLoadExtension('ImageMap');
wfLoadExtension('Linter');
wfLoadExtension('Math');
wfLoadExtension('MultimediaViewer');
wfLoadExtension('ParserFunctions');
wfLoadExtension('PdfHandler');
wfLoadExtension('Poem');
wfLoadExtension('ReplaceText');
wfLoadExtension('Scribunto');
wfLoadExtension('SyntaxHighlight_GeSHi');
wfLoadExtension('TemplateData');
wfLoadExtension('TimedMediaHandler');
wfLoadExtension('UniversalLanguageSelector');
wfLoadExtension('Variables');
wfLoadExtension('VisualEditor');
wfLoadExtension('WikiEditor');
wfLoadExtension('Echo');
wfLoadExtension('InputBox');
wfLoadExtension('Interwiki');
wfLoadExtension('PageImages');
wfLoadExtension('MobileFrontend');


# End of automatically generated settings.
# Add more configuration options below.

$wgGroupPermissions['sysop']['interwiki'] = true;

# TimedMediaHandler
$wgFFmpegLocation = '/usr/bin/ffmpeg'; // Most common ffmpeg path on Linux

$wgULSEnable = false;
