#!/usr/bin/env bash

mariadb --user=root --password=${MYSQL_ROOT_PASSWORD} <<EOF
-- AMOOSIN
CREATE USER IF NOT EXISTS $AMOOSIN_DB_USER@'$MYSQL_HOST' IDENTIFIED BY '$AMOOSIN_DB_PASSWORD';
CREATE DATABASE IF NOT EXISTS $AMOOSIN_DB_NAME CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
GRANT ALL PRIVILEGES ON $AMOOSIN_DB_NAME.* TO $AMOOSIN_DB_USER@'$MYSQL_HOST';
FLUSH PRIVILEGES;

-- ADMIN
GRANT ALL PRIVILEGES ON $AMOOSIN_DB_NAME.* TO $MYSQL_USER@'$MYSQL_HOST' WITH GRANT OPTION;
FLUSH PRIVILEGES;
EOF
