#!/usr/bin/env bash

run_sh_files() {
    local src_path="${1}"

    # Check if the directory exists
    if [ ! -d "$src_path" ]; then
        message_error "Directory not found."
        return 1
    fi

    # Loop through all .sh files in the directory and run them
    for file in "$src_path"/*.sh; do
        if [ -f "$file" ]; then
            source "$file"
        fi
    done
}

extract_extensions() {
    local src_path="${1}"
    local dist_path="${2}"

    # Check if the destination directory exists, create it if it doesn't
    mkdir -p "${EXTENSION_DIR}"

    # Loop through each tar.gz file in the source folder
    for tar_gz_file in "$src_path"/*.tar.gz; do
        if [ -f "$tar_gz_file" ]; then
            # Extract the tar.gz file to the destination path
            tar -xzf "$tar_gz_file" -C "${EXTENSION_DIR}"
            message_success "Extracted '$tar_gz_file' to '$dist_path'"
        fi
    done

}

source_path="${1:-"/extensions"}"

extract_extensions "${source_path}"
run_sh_files "${source_path}"
